package model

//CREATE TABLE albums(
//  id INTEGER PRIMARY KEY,
//  artpath BLOB,
//  added REAL,
//  albumartist TEXT,
//  albumartist_sort TEXT,
//  albumartist_credit TEXT,
//  album TEXT,
//  genre TEXT,
//  year INTEGER,
//  month INTEGER,
//  day INTEGER,
//  disctotal INTEGER,
//  comp INTEGER,
//  mb_albumid TEXT,
//  mb_albumartistid TEXT,
//  albumtype TEXT,
//  label TEXT,
//  mb_releasegroupid TEXT,
//  asin TEXT,
//  catalognum TEXT,
//  script TEXT,
//  language TEXT,
//  country TEXT,
//  albumstatus TEXT,
//  albumdisambig TEXT,
//  rg_album_gain REAL,
//  rg_album_peak REAL,
//  r128_album_gain INTEGER,
//  original_year INTEGER,
//  original_month INTEGER,
//  original_day INTEGER
//);
