#!/bin/ksh

name="gow"
daemon="/home/wise/go/bin/gow"
gow_user="wise"
gow_settings="settings.toml"

rc_stop() {
	echo "stopping..."
	pkill $name
	echo "returned:$?"
}

rc_start() {
	echo "start"
	$name web $gow_settings &
}

if [ $# -eq 1 ] ; then
	echo "arg is: $1"
	if [ $1 == "stop" ] ; then
		rc_stop
	elif [ $1 == "restart" ] ; then
		rc_stop
		sleep 1
		rc_start
	elif [ $1 == "start" ] ; then
		rc_start
	fi
else 
	echo "default is start"
	rc_start
fi

