#!/bin/ksh

name="gwww"
daemon="/home/wise/go/bin/gwww"
gwww_user="wise"
gwww_settings="/home/wise/data/GO/gwww/settings.toml"

rc_stop() {
	echo "stopping..."
	pkill $name
	echo "returned:$?"
}

rc_start() {
	echo "start"
	$name web $gwww_settings &
}

if [ $# -eq 1 ] ; then
	echo "arg is: $1"
	if [ $1 == "stop" ] ; then
		rc_stop
	elif [ $1 == "restart" ] ; then
		rc_stop
		sleep 1
		rc_start
	elif [ $1 == "start" ] ; then
		rc_start
	fi
else 
	echo "default is start"
	rc_start
fi

